name: Bazel Test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Display current directory
        working-directory: ./
        run: echo `pwd`
      - name: Run all tests
        working-directory: ./
        run: |
          bazel test //...
